# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_auto_20171216_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashsettings',
            name='last_cleaning_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 11, 22, 38, 720344, tzinfo=utc)),
        ),
    ]
