# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_auto_20171216_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_log', models.CharField(default='.log_myrm_itislogfilemyrm_', max_length=200)),
                ('path_to_trash', models.CharField(default='/home/mark/PycharmProjects/myrm/.mytrash', max_length=200)),
                ('call_auto_cleaning_if_memory_error', models.BooleanField(default=False)),
                ('dry', models.BooleanField(default=False)),
                ('last_cleaning_date', models.DateTimeField(default=datetime.datetime(2017, 12, 16, 11, 24, 5, 866464, tzinfo=utc))),
                ('level_log', models.IntegerField(default=10)),
                ('max_size_for_start_cleaning', models.IntegerField(default=2000000000)),
                ('min_day_for_start_cleaning', models.IntegerField(default=14)),
                ('policy', models.IntegerField(default=0)),
                ('resolve_conflict', models.BooleanField(default=True)),
                ('show_bar_status', models.BooleanField(default=False)),
                ('silent', models.BooleanField(default=False)),
                ('with_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TrashSettings',
        ),
    ]
