# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_auto_20171216_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashsetting',
            name='last_cleaning_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 11, 24, 59, 785477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trashsetting',
            name='path_to_trash',
            field=models.CharField(default='.mytrash', max_length=200),
        ),
    ]
